---

- name: Install bernhard client for centos
  pip:
    name: bernhard
    executable: /usr/local/bin/pip
  when: ansible_os_family == "RedHat"

- name: Install bernhard client for ubuntu
  pip:
    name: bernhard
  when: ansible_os_family == "Debian"

- name: Create the script for heartbeat
  template:
    src: riemannHeartbeat.py
    dest: /root/riemannHeartbeat.py
    owner: root
    group: root
    mode: 0777

- name: Check if upstart is installed
  command: /usr/bin/which initctl
  register: upstart_stat
  ignore_errors: yes
  when: ansible_os_family == "Debian"

- name: Setup upstart script for heartbeat
  template:
    src: heartbeat.conf
    dest: /etc/init/heartbeat_to_riemann.conf
    owner: root
    group: root
    mode: 0777
  when: ansible_os_family == "Debian" and upstart_stat.stdout == "/sbin/initctl"

- name: Setup upstart script for heartbeat
  template:
    src: heartbeat.conf
    dest: /etc/init/heartbeat_to_riemann.conf
    owner: root
    group: root
    mode: 0777
  when: ansible_os_family == "RedHat"

- name: Check if systemd is present
  command: /usr/bin/which systemd
  register: systemd_stat
  ignore_errors: yes
  changed_when: False
  when: ansible_os_family == "Debian"

- name: Setup systemd script for heartbeat
  template:
    src: heartbeat_to_riemann.service
    dest: /etc/systemd/system/heartbeat_to_riemann.service
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "Debian" and systemd_stat.stdout == "/bin/systemd"

- name: Start the heartbeat script for ubuntu
  service:
    name: heartbeat_to_riemann
    state: started
  when: ansible_os_family == "Debian"

- name: Start the heartbeat script for centos
  command: /sbin/initctl restart heartbeat_to_riemann
  changed_when: false
  when: ansible_os_family == "RedHat"
